const ServicesData = [
  {
    title: "Front End",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/03a9f6fc484719e6ce9349f4a57aae9cb75bdcc9-600x600.svg",
    tags: [
      "HTML5",
      "CSS3",
      "SCSS",
      "JavaScript",
      "TypeScript",
      "React.js",
      "Next.js",
      "JSON",
      "fetch/axios",
      "Jest/Cypress/Testing-library",
      "Material-UI",
      "Bootstrap",
      "Tailwind CSS",
      "Responsive Design"
    ],
  },
  {
    title: "Back End",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/1ca784a9bf93dc47756fdb2cb8a33aeeca20fb75-128x128.svg",
    tags: [
      "Node.js",
      "Express.js",
      "Sequelize",
      "TypeORM",
      "RESTful APIs",
      "Ruby on Rails",
      "Python",
      "PHP",
      "MySQL",
      "MS SQL",
      "PostgreSQL",
      "MongoDB",
      "Firebase"
    ],
  },
  {
    title: "Deployment & Skill",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/f407fcbd4c04d8affdf00209abe608ec708a1388-512x512.svg",
    tags: [
      "WordPress",
      "Docker",
      "AWS Services(ECS, EC2, Lambda, RDS, S3)",
      "Netlify",
      "Git Workflow",
      "CI/CD Pipeline",
      "Agile Methodology",
      "Software Development Life Cycle",
      "Debugging & Hotfix",
      "Collaborating Project",
      "Time Management",
    ],
  },

  {
    title: "Software Tool",
    icon: "https://cdn.sanity.io/images/fxul9ln3/production/a13e377822ec30af9894808787bcacfae6d3d02d-128x128.png",
    tags: [
      "Visual Studio",
      "VSCode",
      "IntelliJ",
      "Github",
      "Jira",
      "Bitbucket",
      "Confluence",
      "pgAdmin/Postico",
      "MySQL Workbench",
      "HeidiSQL",
      "Postman",
      "Custom.io",
      "Zapier",
      "Asana",
      "Microsoft Excel / Word"
    ],
  },
];
export default ServicesData;
